### ISSUE TITLE
Meaningfull variable name

### ISSUE THREAD

**Issue by ajinkya-winsoft** [bharte1993/Calculator#16]
https://github.com/bharte1993/Calculator/blob/0b6ddf83213bd7f83b5b6d5f3a5d0fa2d392ab6a/javascript.js#L10

- the variable name should be meaningful.
-  Avoid single character variable name.
- `.getElementById("d")` here `d` doesn't convey any meaning full information to reader.

**Comment by bharte1993** [comment]
ohk sir , i wil change it.
