### ISSUE TITLE
Proper naming convention

### ISSUE THREAD

**Issue by ajinkya-winsoft** [bharte1993/Calculator#18]
https://github.com/bharte1993/Calculator/blob/0b6ddf83213bd7f83b5b6d5f3a5d0fa2d392ab6a/javascript.js#L24

A variable name should be noun whereas function name should be verbs.
A variable should clearly describe its purpose.
Function perform some actions, hence it is suggested to declare their name as verb, (verb defines what action is being performed)

For Example....
- here the function name `operation` is a noun. It doesn't describe what that function is doing, Instead you can have the name declare as `getOperator`, this suggest that this function will be used to get/return the operator. 
 - Here `getOperator` is a verb
- did you understand why the function name always has the `get` and `set` in their name.

**Comment by bharte1993** [comment]
ohk sir ,i understand and i will change it.
